name: Book Staging

on:
  pull_request:
    branches: [ master ]

jobs:
  docker-build-and-stage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ hashFiles('poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-buildx-${{ hashFiles('poetry.lock') }}

    #  This build and push step does the same thing as `make docker-build`, but
    #  makes it easier to store and load caches, which is why we use it instead
    - name: Build and Save Layers Locally
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        load: true
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        tags: python4compscience

    - name: List Available Images
      run: docker images

    - name: Make Docker HTML
      run: make docker-html

    - name: Make Docker PDF
      run: |
        make docker-pdf
        sudo cp book/_build/latex/book.pdf book/_build/html/book.pdf

    - name: Check links - Markdown
      uses: gaurav-nelson/github-action-markdown-link-check@v1

    # - name: Check links - Muffet
    #   env:
    #     INPUT_URL: https://${{ github.event.repository.owner.name }}.github.io/${{ github.event.repository.name }}
    #     INPUT_PAGES_PATH: ./book/_build/html
    #     INPUT_CMD_PARAMS: --buffer-size=8192 --max-connections=10 --color=always --skip-tls-verification
    #   run: |
    #     wget -qO- https://raw.githubusercontent.com/ruzickap/action-my-broken-link-checker/4a8f10a7cee94ca3db91a09542c9a84b1a25320c/entrypoint.sh | bash

    # Deploy the book's HTML to gh-pages branch
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@bbdfb200618d235585ad98e965f4aafc39b4c501
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: book/_build/html
        destination_dir: staging
